### ISSUE TITLE
suggestion: run user alias

### ISSUE THREAD

**Issue by marozsas** [IkorJefocur/ulauncher-commandrunner#2]
Hi, I am using your extension which is great.
I would like to suggest you a new functionality: The ability to run user alias.
The background:
I have several (a dozen) of alias to connect to pre-defined hosts at work using xfreerdp, something like this:
alias wsrv1='xfreerdp /w:1900 /h:1000 very long list of parameters'
alias wsrv2='xfreerdp /w:1900 /h:1000 very long list of parameters'
alias dbsrv1='xfreerdp /w:1900 /h:1000 very long list of parameters'
... you got the idea...
In a command shell I connect to a host simply typing the desired machine, i.e. wsrv1
To connect to a second computer I have to open a second shell to type the other alias, wsrv2...

Would be great if commandrunner could run, in background, such aliases, since the output it is not important.

I known I can turn theses aliases in a very tiny shell scripts and then I could run it with the same end.
But this is the purpose of aliases isn't ?

best regards,

**Comment by IkorJefocur** [comment]
Added in 1.1.0 (de313452c4ff024911ced9fba1713ccb5cc272d8). All you need is specify command that gets list of your aliases and make sure that your shell can run them in one-command style like "bash -c ...". [Here i wrote some tips about it](https://github.com/IkorJefocur/ulauncher-commandrunner/blob/master/GUIDES.md).

**Comment by marozsas** [comment]
I've followed your guide and its works ONLY IF ulauncher was started on a console.
Next boot, when it starts automatically, the alias and functions didn't work !
Then, I kill ulauncher (ps -ef | grep ulauncher; kill PID) and start it again on command line and this time the alias are available.
Can you help me do debug this issue, please ?

**Comment by IkorJefocur** [comment]
First of all we need to understand what is difference between starting ulauncher at startup and on a console. How startup configured? Is it "launch at login" option in application preferences, system settings or manually created `.desktop` file in `~/.config/autorstart` or something like this? Anyway, if you're somehow specified **application**, not **command** to launch, show me that application file. Probably it's located at `/usr/share/applications/ulauncher.desktop`.
Some logs might be helpful too. Provide me your config for ulauncher and extension both. And output when you starting ulauncher in console.
Also, did you try to disable all other extensions? And did you try to start ulauncher as application (not from console, maybe from other application launcher)?

**Comment by marozsas** [comment]
How startup configured? Answer: Is it "launch at login" option in application preferences.
The problem is related to "command runner" plugin and bash alias and also bash functions, tested both. I type "r wsrv1" and If it was started on a terminal, as soon I type a few letters as "r wsr" I am presented with 2 choices: "wsrv1" and "wsrv2", both are in the output of command list getter (I modified it to work with functions, but the problem happens with alias too).
Currently, I am using "bash -ci 'declare -F' | awk '{print $3}'" as command list getter.
As suggested, starting ulauncher from default gnome launcher (ALT+F2 -> "Run a command") it behaves like it was autostarted, I mean, the alias/functions expansion did not work.
Disabling all other extensions (only 4: Network Manager, SSH launcher, CoinGecko and Command Runner) did not make any difference.
Files:
 https://free.keep.sh/OmoqFWPy2kcLjFY0/extensions.json/download
 https://free.keep.sh/QF282rKSTO5GcyC1/anypaste.tG9EtzB38r.tar.gz/download
https://free.keep.sh/53nofsRmMh5ifnm2/settings.json/download
https://free.keep.sh/4jJOGdSFR3sNe7ZS/shortcuts.json/download
https://hastebin.com/raw/ejerosorav

**Comment by IkorJefocur** [comment]
Please show me output of `cat /usr/share/applications/ulauncher.desktop`.

**Comment by marozsas** [comment]
[Desktop Entry]
Name=Ulauncher
Comment=Application launcher for Linux
GenericName=Launcher
Categories=Utility;Accessibility;
TryExec=/usr/bin/ulauncher
Exec=env GDK_BACKEND=x11 /usr/bin/ulauncher --hide-window
Icon=ulauncher
Terminal=false
Type=Application

**Comment by IkorJefocur** [comment]
Try to start ulauncher from console by command `env GDK_BACKEND=x11 /usr/bin/ulauncher --hide-window`. Maybe play with arguments and environment variables. Is problem repeats and in which cases?

**Comment by marozsas** [comment]
Starting from console by "env GDK_BACKEND=x11 /usr/bin/ulauncher --hide-window" works as expected, I mean, typing "r ws" is enough to get the both options "wsrv1"and "wsrv2".

**Comment by IkorJefocur** [comment]
Go to extension folder (`cd ~/.local/share/ulauncher/extensions/com.github.ikorjefocur.ulauncher-commandrunner/`). Swap version of command runner to branch "#2-alias-debug" (`git checkout "#2-alias-debug"`).
Then (re)start ulauncher as an application, make sure that extension loaded and show me contents of `debug.log` file in extension folder.

**Comment by marozsas** [comment]
hi,
sorry, I didn´t get what do you mean by "Swap version of command runner to branch "#2-alias-debug" 
can you elaborate, please ?

**Comment by IkorJefocur** [comment]
Just enter this commands in terminal:
```
cd ~/.local/share/ulauncher/extensions/com.github.ikorjefocur.ulauncher-commandrunner/
git checkout "#2-alias-debug"
```

**Comment by marozsas** [comment]
git checkout "#2-alias-debug"                                                                                                            SIGINT 
fatal: not a git repository (or any parent up to mount point /)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).

**Comment by IkorJefocur** [comment]
```

**Comment by IkorJefocur** [comment]
This is because ulauncher removes any git information after cloning extension repo. Try this:
```
cd ~/.local/share/ulauncher/extensions/com.github.ikorjefocur.ulauncher-commandrunner/
git init
git remote add origin https://github.com/IkorJefocur/ulauncher-commandrunner
git add -A
git pull origin "#2-alias-debug"
```

**Comment by marozsas** [comment]
I am not sure how to fix this error:
git pull origin "#2-alias-debug"                                                                                                        master 
remote: Enumerating objects: 68, done.
remote: Counting objects: 100% (68/68), done.
remote: Compressing objects: 100% (40/40), done.
remote: Total 68 (delta 36), reused 57 (delta 26), pack-reused 0
Unpacking objects: 100% (68/68), 12.14 KiB | 888.00 KiB/s, done.
From https://github.com/IkorJefocur/ulauncher-commandrunner
 * branch            #2-alias-debug -> FETCH_HEAD
 * [new branch]      #2-alias-debug -> origin/#2-alias-debug
error: Your local changes to the following files would be overwritten by merge:
	main.py
Please commit your changes or stash them before you merge.
Aborting

**Comment by IkorJefocur** [comment]
Ok, seems like here's better way:
```
cd ~/.local/share/ulauncher/extensions
rm -rf com.github.ikorjefocur.ulauncher-commandrunner
git clone https://github.com/IkorJefocur/ulauncher-commandrunner com.github.ikorjefocur.ulauncher-commandrunner --branch "#2-alias-debug"
```

**Comment by marozsas** [comment]
I double checked that the  folder com.github.ikorjefocur.ulauncher-commandrunner was removed from ~/.local/share/ulauncher/extensions and the gitclone recreated it. Fine.
But there is no debug.log file under ~/.local/share/ulauncher/extensions (cd~/.local/share/ulauncher/extensions; find .  -iname '*.log') no matter if I run ulauncher on a terminal or not or if "r any-command" succeeded or not)
Of course I've killed the process before I removed the folder.

**Comment by IkorJefocur** [comment]
Strange. File should contained at `~/.local/share/ulauncher/extensions/com.github.ikorjefocur.ulauncher-commandrunner/debug.log` and created after preferences are inited, probably it's after ulauncher was started or at least when extension directly needed. Try to check you did everything right, run this:
```
cd `~/.local/share/ulauncher/extensions/com.github.ikorjefocur.ulauncher-commandrunner
git status
```
You should be on branch `#2-alias-debug`.

**Comment by marozsas** [comment]
Hi, 
Follow:

 miguel$  ls ~/.local/share/ulauncher/extensions/com.github.ikorjefocur.ulauncher-commandrunner/debug.log
"/home/miguel/.local/share/ulauncher/extensions/com.github.ikorjefocur.ulauncher-commandrunner/debug.log": No such file or directory (os error 2)
 miguel$ cd ~/.local/share/ulauncher/extensions/com.github.ikorjefocur.ulauncher-commandrunner                                                                                                                           
 miguel$ git status
On branch #2-alias-debug
Your branch is up to date with 'origin/#2-alias-debug'.

nothing to commit, working tree clean
 miguel$
