### ISSUE TITLE
Add support for expanding `~`

### ISSUE THREAD

**Issue by glyh** [IkorJefocur/ulauncher-commandrunner#3]
As title, right now the commandrunner does not recognize this hortcut, and I think it would be handy if this can be supported

**Comment by IkorJefocur** [comment]
Added in 1.0.0 ([a89c96b](https://github.com/IkorJefocur/ulauncher-commandrunner/commit/a89c96bfd3366b4afc339b59f3dce3deaa3f57d7)). You only need to specify your shell in preferences and then you can use this shortcut as well as other shell features.

**Comment by glyh** [comment]
Thanks a lot!
